# Generated by Django 2.2.26 on 2022-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopussource',
            name='source_id',
            field=models.BigIntegerField(),
        ),
    ]
