# Generated by Django 2.2.26 on 2022-02-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_auto_20220202_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopusclassification',
            old_name='classification_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='scopusclassification',
            old_name='classifictiion_name',
            new_name='name',
        ),
    ]
