# Generated by Django 2.2.27 on 2022-02-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20220202_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopusclassification',
            name='category_abbr',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='scopusclassification',
            name='category_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
