# Generated by Django 2.2.27 on 2022-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_search_searchresult_category_searchresult_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult_entry',
            name='document_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
