# Generated by Django 2.2.27 on 2022-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0008_searchresult_entry_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopussource',
            name='e_issn',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scopussource',
            name='p_issn',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
