# Generated by Django 2.2.27 on 2022-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0009_auto_20220216_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult_entry',
            name='doi',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
