# Generated by Django 2.2.27 on 2022-02-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0010_searchresult_entry_doi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopusclassification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scopussource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='searchresult_category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='scopusclassification',
            unique_together={('code',)},
        ),
        migrations.AlterUniqueTogether(
            name='scopussource',
            unique_together={('source_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='searchresult_category',
            unique_together={('search', 'category_abbr')},
        ),
        migrations.AlterUniqueTogether(
            name='searchresult_entry',
            unique_together={('search', 'category_abbr', 'scopus_id')},
        ),
    ]
