# Generated by Django 2.2.27 on 2022-02-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0011_auto_20220223_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult_entry',
            name='publication_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
