# Generated by Django 2.2.27 on 2022-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0012_auto_20220226_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
