# Generated by Django 2.2.28 on 2022-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0013_search_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='job_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
